// Code generated by templ - DO NOT EDIT.

// templ: version: 0.2.476
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func CreateSession() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
			if !templ_7745c5c3_IsBuffer {
				templ_7745c5c3_Buffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<h1 class=\"flex justify-center text-center px-5 pt-14 pb-10 min-[601px]:pt-28 min-[601px]:pb-20 text-3xl font-extrabold underline\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Var3 := `Create a poll`
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</h1><div class=\"mx-auto overflow-hidden align-middle px-4 min-[601px]:text-center bg-[#FCFDFC]\"><form action=\"/createPoll\" method=\"post\"><div id=\"formInputs\" class=\"mx-auto w-full pr-16 p-5 mt-5 min-[601px]:mt-10 min-[601px]:py-10 min-[601px]:pl-0 max-w-[900px] h-[27rem] overflow-y-auto overscroll-auto min-[601px]:overscroll:contain scrollbar-gutter-stable shadow-lg shadow-slate-200 rounded\"><label for=\"title\" class=\"text-xl float-left w-full min-[601px]:w-1/5\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Var4 := `Title`
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var4)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</label> <input type=\"text\" id=\"title\" name=\"title\" placeholder=\"Title\" class=\"w-full min-[601px]:w-4/5 p-5 mb-6 border rounded-sm border-solid border-gray-400\"><br><div class=\"border-t-2 border-dashed\"></div><label for=\"inputAnswer1\" class=\"text-xl float-left w-full mt-6 min-[601px]:w-1/5\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Var5 := `Answer`
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var5)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</label> <input type=\"text\" id=\"inputAnswer1\" name=\"inputAnswer\" placeholder=\"Answer\" class=\"w-full min-[601px]:w-4/5 min-[601px]:mt-6 p-5 border rounded-sm border-solid border-gray-400\"><br><label for=\"inputAnswer2\" class=\"text-xl float-left w-full mt-4 min-[601px]:w-1/5\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Var6 := `Answer`
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var6)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</label> <input type=\"text\" id=\"inputAnswer2\" name=\"inputAnswer\" placeholder=\"Answer\" class=\"w-full min-[601px]:w-4/5 min-[601px]:mt-4 p-5 border rounded-sm border-solid border-gray-400\"><br></div><div class=\"mx-auto flex flex-col gap-4 my-10 max-w-[900px]\"><button id=\"addPollAnswerBtn\" type=\"button\" class=\"max-w-[300px] text-[#809D80] py-5 duration-300 cursor-pointer border-2 border-[#809D80] hover:underline rounded\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Var7 := `Add answer`
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var7)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</button> <input type=\"submit\" value=\"Create poll\" class=\"max-w-[300px] whitespace-normal bg-[#809D80] text-zinc-50 py-5 px-5 duration-300 cursor-pointer border-2 border-slate-950 hover:bg-[#5c735c] hover:text-white rounded\"></div></form></div><script>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Var8 := `
            (function() {
                var counter = 2;
                var btn = document.getElementById('addPollAnswerBtn')
                var form = document.getElementById('formInputs')

                var addInput = function() {
                    counter++;
                    var label = document.createElement("label");
                    var input = document.createElement("input");
                    var br = document.createElement('br');
                    label.htmlFor = 'inputAnswer' + counter;
                    label.className = 'text-xl float-left w-full mt-4 min-[601px]:w-1/5'
                    label.innerHTML = 'Answer'

                    input.type = 'text';
                    input.id = 'inputAnswer' + counter;
                    input.name = 'inputAnswer';
                    input.placeholder = 'Answer'
                    input.className = 'w-full min-[601px]:w-4/5 min-[601px]:mt-4 p-5 border rounded-sm border-solid border-gray-400';
                    form.appendChild(label);
                    form.appendChild(input);
                    form.appendChild(br);
                };

                btn.addEventListener('click', function() {
                    addInput();
                    form.scrollTo({ top: form.scrollHeight, behavior: 'smooth' });
                }.bind(this));
            })();

        `
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var8)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</script>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if !templ_7745c5c3_IsBuffer {
				_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = Head("GoPoll | Create session").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
